### ISSUE TITLE
Announcement Error

### ISSUE THREAD

**Issue by iron217** [SacredDuckwhale/Rarity#135] opened 2019-10-20 14:56 UTC
error when addon try to announce message about the event in the chat and freezes the system,
re-recorded the video several times so it did not always display an event message

rarity 692 ruru client

only addon are included: ACP, Buggrabber and Bugsack

https://drive.google.com/file/d/1iHUTx2hGsZ8KXL1Ysc2qljD8k_3t1YNo/view?usp=sharing

```
1x ...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:342: attempt to perform arithmetic on field '_paddingL' (a nil value)
...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:342: in function `getContentHeight'
...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:919: in function <...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:865>
...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:210: in function <...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:206>

Locals:
self = <unnamed> {
 0 = <userdata>
 _provider = <table> {
 }
 fontString = <unnamed> {
 }
}
fontString = <unnamed> {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field '_paddingL' (a nil value)"
```

**Comment by SacredDuckwhale** [comment] 2019-11-06 19:48
Duplicate of https://github.com/SacredDuckwhale/Rarity/issues/136

**Closed by SacredDuckwhale** 2019-11-06 19:48 UTC
