### ISSUE TITLE
Minimap Icon Hover Request

### ISSUE THREAD

**Issue by chillface** [SacredDuckwhale/Rarity#207] opened 2020-10-19 20:27 UTC
Any chance there can be an option to change the minimap icon to be clickable instead of hovering over to show the Rarity information? Theres been many times I have hovered over it accidentally and my farming list information fills my screen. Would love to have it only display when i click it if possible.

**Comment by SacredDuckwhale** [comment] 2020-10-20 01:37
If I understand you correctly, this is a duplicate of https://github.com/SacredDuckwhale/Rarity/issues/197

**Closed by SacredDuckwhale** 2020-10-20 01:37 UTC

**Comment by chillface** [comment] 2020-10-20 02:35
yes exactly, sorry i didnt see that one posted already!
