### ISSUE TITLE
Missing LibBabble-Zone-3.0

### ISSUE THREAD

**Issue by GaryREM** [SacredDuckwhale/Rarity#38] opened 2018-07-31 21:00 UTC
New error on r666-beta-nolib.

12x Rarity\Core.lua:26: Cannot find a library instance of "LibBabble-Zone-3.0".
[C]: in function `error'
Ace3\LibStub\LibStub-1.0.2-70000.lua:23: in function `LibStub'
Rarity\Core.lua:26: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBabble-Zone-3.0"."

Seems like this library has been abandoned since 2012...

**Comment by SacredDuckwhale** [comment] 2018-08-01 14:38
Please see my last comment on this similar issue: https://github.com/SacredDuckwhale/Rarity/issues/37

The library may be outdated, but the problem is that no-lib versions include no libraries.

**Comment by GaryREM** [comment] 2018-08-01 15:01
I guess I wasn't clear. The library was deprecated 3 WoW versions ago. It appeared to indicate its functionality was now available in the WoW API. So I was assuming it would be a good idea to eliminate the library from your code.

**Comment by SacredDuckwhale** [comment] 2018-08-02 06:46
Oh, yeah. There's lots of ancient stuff still in the addon's code, but I haven't had time to go through it and see what can be thrown out. Some things might need changing or break if I suddenly removed them all, so I've left them in. For now...

The question is, how does this cause any errors for you? Said library may not be updated for newer expansions, but it otherwise works as it used to. There shouldn't be any "new errors" unless the library isn't installed, which is what my "no-lib" comment was directed at.

**Comment by SacredDuckwhale** [comment] 2018-08-03 18:10
I've consulted Allara on this, and the library is actually still used for subzone detection, which is required for certain items (e.g., Mr. Pinchy or the Giant Sewer Rat).

I'll look into finding a more modern way of doing this using the API, but that'll be a different issue. Therefore I'm closing this as invalid (since the library isn't actually missing). If the error persists and is unrelated to running a no-lib release, please report back and I'll investigate further.

**Closed by SacredDuckwhale** 2018-08-03 18:10 UTC
