### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by N6REJ** [SacredDuckwhale/Rarity#178] opened 2020-05-15 03:02 UTC
I'm getting the following script error...

> Message: ...rface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:1020: script ran too long
Time: Thu May 14 21:59:45 2020
Count: 1
Stack: ...rface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:1020: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:1020: in function <...rface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:930>
[string "@Interface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:1092: in function <...rface\AddOns\Rarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:1058>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Rarity\Core\GUI.lua"]:1498: in function <Interface\AddOns\Rarity\Core\GUI.lua:1127>
[string "@Interface\AddOns\Rarity\Core\GUI.lua"]:1724: in function `ShowTooltip'
[string "@Interface\AddOns\Rarity\Core\GUI.lua"]:404: in function `OnEnter'
[string "@Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:77: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>
Locals:

**Comment by SacredDuckwhale** [comment] 2020-07-01 17:54
Duplicate of https://github.com/SacredDuckwhale/Rarity/issues/136, I think?

**Closed** 2020-07-01 17:54 UTC
Labels: status:duplicate
